### ISSUE TITLE
Jitsi Räume

### ISSUE THREAD

**Issue by wolf128058** [Weltenwanderer/WeltiConRoom#11]
Für größere Tische, Bällebäder, etc sollte nicht das Umkreissystem für Jitsi gezogen werden, sondern dedizierte Jitsi Räume.

**Comment by wolf128058** [comment]
Klappt ganz gut mit separater Ebene und definiertem Attribut "jitsiRoom" (string)

**Comment by NathanaelDracon** [comment]
hab es fürs Cafe und den Pen & Paper bereich auch hinzugefügt

**Comment by wolf128058** [comment]
meinetwegen schließbar :-)

**Comment by NathanaelDracon** [comment]
done
