### ISSUE TITLE
CERTifizierung

### ISSUE THREAD

**Issue by wolf128058** [Weltenwanderer/WeltiConRoom#24]
Das Chaos Emergency Response Team (CERT) zertifiziert oder eben certifiziert Räume, die gewisse Sicherheitsfeatures haben.
(s. https://events.ccc.de/2020/12/12/rc3-how-to-aktive-teilnahme/#more-9079 unter "CERT online")
![grafik](https://user-images.githubusercontent.com/946255/102280728-f9aee900-3f2d-11eb-9320-60bbbbbd3c74.png)

Obligatorisch:
- Brandschutz (Feuerlöscher/Löschdecken)
- Beschilderte Notausgänge
- Abgesicherte Gefahrenstellen(Flatterband, Hütchen, etc.)
- Erste-Hilfe-Kasten

**Comment by wolf128058** [comment]
Tiles gibts hier: https://tiles.rc3.world/community/cert/imgs/cert_safety/

**Comment by wolf128058** [comment]
Da muss noch ein Erste-Hilfe-Kasten irgendwohin aber das Dingen aus dem Tile-Pool kann kaum jemand erkennen.
Bessere Grafik erwünscht.

**Comment by Thorsten-Sick** [comment]
Geht dann mein Mate-Kisten-Turm-des-Todes und das Katapult im Garten ?

**Comment by wolf128058** [comment]
Absperrband drum rum und dann aber bitte ja!
Mit PR #32 bekommst du im Garten rechts einen abgesperrten Cyber-Bereich zum Austoben :-)

**Comment by wolf128058** [comment]
Wir sind CERTifiziert. Ich schließe.
