### ISSUE TITLE
Collision/Layer Testen

### ISSUE THREAD

**Issue by wolf128058** [Weltenwanderer/WeltiConRoom#28]
Bitte mal testen, wo Kollisionen sinnvoll wären oder auch Layer falsch laufen.

- Ich kann der Statue auf den Kopf treten?
- Der Hut/Helm bei der Rüstung ist nicht drauf sondern liegt daneben und man kann drauf treten.

Könnte man mal im Hausfrauentestverfahren mal ermitteln ;-)

**Comment by wolf128058** [comment]
Aktuell im PenAndPaper nach bestem Wissen gefixt.
GGf. nochmal testen bitte.

**Comment by NathanaelDracon** [comment]
sieht super aus thx

**Comment by wolf128058** [comment]
na dann schließe ich.
