### ISSUE TITLE
Labels/Signs

### ISSUE THREAD

**Issue by wolf128058** [Weltenwanderer/WeltiConRoom#59]
Found a nice tool to create text on tiles:
https://rc3.pages.git.cccv.de/world-maps/tools/textGenerator.html

According to the [Styleguide](https://styleguide.rc3.world/RC3%20Style%20Guide%20Essentials.pdf) the preferred Fonts are Orbitron and Montserrat

Feel free to play with that tool and please create more labels just to give our visitors the best user experience :-)

**Comment by wolf128058** [comment]
@JohannesRitz: Please replace your Text-Layers e.g. in BoardGame/showroom.json with this feature.
Otherwise nobody will see your Text-Information

**Comment by wolf128058** [comment]
labels for the rooms in BoardGame/BoardGame_main.json would still be nice.

**Comment by JohannesRitz** [comment]
Thanks for those labels. I continued the tradition.

**Comment by wolf128058** [comment]
gefixt. close
