### ISSUE TITLE
404 im Labyrinth

### ISSUE THREAD

**Issue by johannes-hafner** [Weltenwanderer/WeltiConRoom#67]
Im Labyrinth kann man den Friedhof (?? Der URL nach wohl :D) nicht betreten: "Could not load map https://visit.at.rc3.world/as/lobby/wZjkhkDWam1F3CJSYGrpcB/_/global/spielekiste.maps.at.rc3.world//Labyrinth/Labyrinth_Entry.json". Da passt irgendwas nicht. (target ist #startLayerGraveyard)

Ich nehme an, korrekt wäre: https://visit.at.rc3.world/as/lobby/wZjkhkDWam1F3CJSYGrpcB/_/global/spielekiste.maps.at.rc3.world//Labyrinth/Labyrinth_main.json#startLayerGraveyard

**Comment by wolf128058** [comment]
Danke, schau ich mir gleich an.

**Comment by wolf128058** [comment]
Labyrinth ist noch WIP. Entsprechender Branch ist noch nicht gemerged.

**Comment by wolf128058** [comment]
Ich hab den Zugang vom master-Branch jetzt einfach mal vorübergehend geschlossen.
Dann kommts zu keinen ungewollten Verirrungen.

**Comment by wolf128058** [comment]
close as wontfix
